name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.4.0
  google_fonts: ^6.3.0
  shimmer: ^3.0.0
  lottie: ^3.3.1
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  supabase: ^2.8.0
  supabase_flutter: ^2.9.1
  flutter_supabase_chat_core: ^1.6.0
  google_nav_bar: ^5.0.7
  crystal_navigation_bar: ^1.0.4
  iconly: ^1.0.1
  json_serializable: ^6.9.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.14.4
  carousel_slider: ^5.1.1

flutter:
  uses-material-design: true

  assets:
    - assets/animations/

# Splash screen config
flutter_native_splash:
  color: "#ffffff" # background color
  image: assets/animations/appIcon.png
  android: true
  ios: true
  web: false

  # Optional dark mode
  color_dark: "#000000"
  image_dark: assets/animations/appIcon.png

# App icon config
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/animations/appIcon.png"
